# Generated by Django 6.0.3 on 2026-03-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('base_unit_name', models.CharField(default='Piece', help_text="The smallest unit, e.g., 'Piece'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('base_unit_stock_level', models.IntegerField(default=0, help_text='Stock level stored in the smallest unit (base units)')),
                ('retail_price_per_base_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price_per_base_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='users.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
            },
        ),
        migrations.CreateModel(
            name='ProductDerivative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivative_name', models.CharField(help_text="e.g., 'Carton' or 'Box'", max_length=50)),
                ('conversion_rate', models.PositiveIntegerField(help_text='How many base units are in this derivative (e.g., 36 pieces in 1 carton)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Derivative',
                'verbose_name_plural': 'Product Derivatives',
            },
        ),
    ]
