# Generated by Django 6.0.3 on 2026-03-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debt', '0001_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', max_length=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('MKOPO', 'Mkopo (Debt)')], default='CASH', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('local_timestamp', models.DateTimeField(help_text='The timestamp from the PWA device when sale occurred.')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.branch')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_handled', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='debt.customer')),
            ],
            options={
                'verbose_name': 'Sale Transaction',
                'verbose_name_plural': 'Sale Transactions',
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(help_text='In base units')),
                ('unit_price_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_entries', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saletransaction')),
            ],
            options={
                'verbose_name': 'Sale Line Item',
                'verbose_name_plural': 'Sale Line Items',
            },
        ),
    ]
